# This is a basic workflow to help you get started with Actions

name: Build and Unit test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the devel branch
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: ubuntu-latest
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - run: npm i -g yarn || true # Not necessary on Github but useful to test locally with `act`
      - run: yarn install --frozen-lockfile --check-files

      #build:
      #  runs-on: ubuntu-latest
      #  needs: install
      #
      #    steps:
      - run: yarn run build
      # Steps represent a sequence of tasks that will be executed as part of the job
      #  steps:
      - run: yarn run test #:unit
