# Use https://github.com/nektos/act to test actions locally
# act

name: Build and Unit test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the devel branch
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: ubuntu-latest
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - name: Install Yarn (if needed)
        run: npm i -g yarn || true # Not necessary on Github but useful to test locally with `act`
      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      #build:
      #  runs-on: ubuntu-latest
      #  needs: install
      #
      #    steps:
      - name: Build
        run: yarn run build
      # Steps represent a sequence of tasks that will be executed as part of the job
      #  steps:
      - name: Run tests
        run: yarn run test #:unit
        # At the moment, this doesn't fail the workflow
        # Because a lot of dependencies will be incorrect until we stabilize Vulcan NPM a bit more
      - name: Check dependencies
        run: yarn run depcheck || true
        # This doesn't fail the workflow, because it can only fail for unit test and stories
      - name: Check types
        run: yarn run typecheck || true
